---
title: "multispic diagnostics and results"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, echo=FALSE}
library(plotly)
library(viridis)
knitr::opts_chunk$set(echo = FALSE, fig.height = 7, fig.width = 8, cache = FALSE)
```


```{r options}

if (fit$call$K_groups == ~1) {
    K_groups <- NULL
    if (length(unique(fit$landings$species)) == 1) {
        K_label <- "K"
    } else {
        K_label <- "All species"
    }
} else {
    K_groups <- as.formula(fit$call$K_groups)
    K_label <- unique(fit$landings[, all.vars(K_groups)])
}

n_covar <-  length(all.vars(fit$call$pe_covariates))

add_labels <- function(p, xlab = "", ylab = "", log_linear_button = TRUE) {
    
    if (log_linear_button) {
        ## Modified from https://stackoverflow.com/a/60551263/4055438
        buttons <- list(list(
            active = 0,
            type = "buttons",
            buttons= list(
                list(label = 'linear',
                     method = 'relayout',
                     args = list(list(yaxis = list(type = 'linear', title = ylab)))),
                list(label = 'log',
                     method = 'relayout', 
                     args = list(list(yaxis = list(type = 'log', title = ylab)))))))
    } else {
        buttons <- NULL
    }
    
    layout(p, 
           xaxis = list(title = xlab),
           yaxis = list(title = ylab),
           updatemenus = buttons)
    
}


```


Inputs
================================================================================

Row {.tabset}
--------------------------------------------------------------------------------

### Index

```{r}
fit$index %>%
    plot_ly() %>%
    add_trace(x = ~year, y = ~index, color = ~survey,
              colors = viridis::viridis(100), mode = "markers+lines",
              type = "scatter") %>% 
    add_labels(xlab = "Year", ylab = "Index")
```


### Landings

```{r}
fit$landings %>%
    plot_ly() %>%
    add_trace(x = ~year, y = ~landings, color = ~species,
              colors = viridis::viridis(100), mode = "markers+lines",
              type = "scatter") %>% 
    add_labels(xlab = "Year", ylab = "Landings")
```


### Covariates

`r if (n_covar == 0) "N/A; no process error covariates supplied"`
`r if (n_covar > 1) "Plotting of more than one covariate not yet implemented"`

```{r, eval = n_covar == 1}
covariates <- unique(fit$landings[, c("year", all.vars(fit$call$pe_covariates)), drop = FALSE])
names(covariates) <- c("year", "covariate")
covariates %>% 
    plot_ly(x = ~year, y = ~covariate) %>% 
    add_trace(mode = "markers+lines") %>% 
    layout(xaxis = list(title = "Year"),
           yaxis = list(title = all.vars(fit$call$pe_covariates)))
```



Residuals
================================================================================

Row {.tabset}
--------------------------------------------------------------------------------

### Index

```{r}

```


Parameters
================================================================================

Row {.tabset}
--------------------------------------------------------------------------------

### Correlation

```{r}

sd_rep <- fit$sd_rep
dsd <- sqrt(diag(sd_rep$cov.fixed))
cor_mat <- diag(1 / dsd) %*% sd_rep$cov.fixed %*% diag(1 / dsd)
rownames(cor_mat) <- paste0(seq(nrow(cor_mat)), ":", names(dsd))
colnames(cor_mat) <- paste0(seq(nrow(cor_mat)), ":", names(dsd))
# corrplot::corrplot.mixed(cor_mat, diag = "n", lower = "ellipse", upper = "number")
plot_ly(x = rownames(cor_mat), y = colnames(cor_mat), z = cor_mat) %>% 
    add_heatmap(colors = c("#B2182B", "white", "#2166AC")) %>% 
    colorbar(limits = c(-1.001, 1.001))

```

### log(K)

```{r}
plot_post(prior_mean = fit$par$mean_log_K,
          prior_sd = exp(fit$par$log_sd_log_K),
          post_mean = fit$par$log_K,
          post_sd = fit$se$log_K,
          post_names = K_label,
          xlab = "log(K)",
          show_prior = fit$call$log_K_option$option == "normal_prior")
```

### log(r)

```{r}
plot_post(prior_mean = fit$par$mean_log_r,
          prior_sd = exp(fit$par$log_sd_log_r),
          post_mean = fit$par$log_r,
          post_sd = fit$se$log_r,
          post_names = levels(fit$landings$species),
          xlab = "log(r)",
          show_prior = fit$call$log_r_option$option == "normal_prior")
```


### log(B0)

```{r}
plot_post(prior_mean = fit$par$mean_log_B0,
          prior_sd = exp(fit$par$log_sd_log_B0),
          post_mean = fit$par$log_B0,
          post_sd = fit$se$log_B0,
          post_names = levels(fit$landings$species),
          xlab = "log(B0)",
          show_prior = fit$call$log_B0_option$option == "normal_prior")
```



Population trends
================================================================================

```{r}

```

